name: Test
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go environment
        uses: actions/setup-go@v3.0.0
        with:
          go-version: 1.18.0-rc.1
      - uses: actions/checkout@v3.0.0
      - run: go test -coverprofile=profile.cov ./...
      - uses: shogo82148/actions-goveralls@v1.5.1
        with:
          path-to-profile: profile.cov